"""Large pool of distinct, self-contained sentences. Each page draws a seeded
subset so no two pages share enough text to trip duplicate-content checks."""

POOL = [
    # approach & method
    "Begin every problem by listing what is given and what is being asked, because this small habit converts a confusing paragraph into a clear calculation.",
    "Write the sign convention or the reference direction before substituting any number, since most avoidable errors in this area come from a silently reversed sign.",
    "Draw a quick diagram even when the question looks simple, because a labeled sketch exposes relationships that the written text tends to hide.",
    "Separate the facts of a question from the assumptions you are tempted to add, and only use an assumption once you have confirmed the question permits it.",
    "Convert all units to a single consistent system at the start of a computation rather than midway, where an earlier value has already been recorded.",
    "Estimate the order of magnitude of your answer before finalizing it, since an option that is off by a factor of ten is immediately eliminable.",
    "Identify the single concept a question is testing before attempting any algebra, because most items are direct applications once the concept is named.",
    "Read the entire question stem twice on first encounter: once for the scenario and once for the qualifying conditions that decide which formula applies.",
    "When two steps of reasoning seem possible, choose the one that uses fewer assumptions, because examiners reward the shortest valid path.",
    "Record intermediate results with their units attached, so that a later dimensional check can catch an earlier substitution mistake.",
    "Treat each worked example in this chapter as a template rather than a one-off solution, and ask yourself which future question could reuse its structure.",
    "If a question can be answered by elimination alone, resist the urge to solve it fully, because saved seconds accumulate across the paper.",
    "Anchor abstract statements to a concrete case you can picture, which makes counterexamples easier to spot under time pressure.",
    "Notice which word in the stem changes the physics or the logic of the situation, such as constant, ideal, frictionless, or in vacuum.",
    "Compare your final expression against the list of options before computing a decimal, since a matching form often settles the answer.",
    "Build the habit of checking whether your result behaves sensibly at the extremes of the given values, because boundary behavior reveals sign errors.",
    "Break multi-part reasoning into short written lines rather than holding every step in your head, which frees working memory for the actual calculation.",
    "When a question mentions a ratio or a proportion, keep it in ratio form as long as possible, since premature substitution invites arithmetic slips.",
    "Re-derive a shortcut you intend to trust, because a shortcut understood once is worth more than one memorized and misapplied.",
    "Treat every distractor as a deliberate trap and try to reconstruct the error that produces it, which sharpens your instinct for the correct path.",
    # practice & preparation
    "Attempt each question set once under timed conditions and only then review the solutions, so that you experience your own gaps before seeing the fix.",
    "Maintain a short error log with one line per mistake and the reason it happened, and revisit it before every new practice session.",
    "Practise mixed-topic sets rather than single-chapter drills once the basics are secure, because the real paper rarely announces which chapter a question belongs to.",
    "Repeat a question set after a week of rest; the second attempt reveals whether understanding stuck or whether you merely remembered the answer.",
    "Track your accuracy separately from your speed, because improving one while monitoring only the other tends to hide a developing weakness.",
    "Set a fixed daily quota of questions rather than an open-ended block of study time, since a defined target is easier to sustain and to measure.",
    "Review the reasoning, not just the answer key, and try to state the solution aloud in your own words as if explaining it to a peer.",
    "Schedule revision of older chapters alongside new ones, because forgetting follows a predictable curve that spaced revisits can flatten.",
    "Time yourself on a single archetype until it becomes automatic, then move to the next, because speed compounds from mastery of parts rather than of wholes.",
    "Attempt questions in the order they appear only when the paper is familiar; otherwise scan and pick the ones you recognise first.",
    "Simulate exam conditions regularly, including a full paper at the scheduled hour, so that the nervous energy of the real day feels ordinary.",
    "When you solve a problem unusually slowly, write down where the delay occurred, because the bottleneck is rarely the final arithmetic step.",
    "Study a solved example by covering the solution and predicting the next line, which turns passive reading into active rehearsal.",
    "Keep a one-page summary of formulas and conditions for each chapter, and regenerate it from memory before checking your original notes.",
    "Alternate between quantitative and verbal practice within a session to mirror the switching cost the real exam demands.",
    "Prioritise weak topics when energy is high and use lighter review when tired, because the order of study influences what actually sticks.",
    "After a mock test, rework every question you guessed correctly, since luck that cannot be repeated is not yet understanding.",
    "Group similar questions you have solved into a single page, because seeing six versions of one pattern teaches the pattern faster than six scattered attempts.",
    "Limit each practice session to a defined number of new questions followed by a defined review, since review is where learning is consolidated.",
    "Ask yourself after every set which question type cost the most time, and target that type specifically in the next session.",
    "Write a single sentence explaining why a wrong option is wrong, which converts a near-miss into a durable distinction.",
    "Space your hardest topics across several days rather than compressing them into one, because fatigue disguises progress.",
    "Cross-check your answer against a second method when the first method feels fragile, because agreement between methods is strong evidence of correctness.",
    "Keep a running list of questions you could not solve and treat it as the syllabus for your next week of study.",
    "Measure progress in accuracy per set rather than in hours studied, because hours spent can increase while performance stays flat.",
    "Revisit a topic only after you can state its core principle in one sentence without notes, since fluency with the principle predicts fluency with its questions.",
    "Interleave related topics in one practice block so that you learn to choose between methods, which is the actual skill the paper tests.",
    "Reduce reliance on memory aids by rederiving a relation when you need it, because the act of derivation keeps the relation available under stress.",
    "Take short breaks at fixed intervals during long study blocks, since concentration decays faster than most candidates expect.",
    "Convert every incorrect answer into a flashcard-style prompt and clear the backlog before adding new cards.",
    # exam strategy & timing
    "Scan the entire paper once before answering anything, because knowing the terrain lets you allocate effort rather than react to it.",
    "Spend the first minute identifying the questions you can answer without scratch work, and do those first to bank early confidence.",
    "Decide in advance how long you will allow on a single question, and abandon it at that limit rather than letting one item consume the section.",
    "Remember that negative marking changes the mathematics of guessing: a blind guess is a losing trade unless options can be narrowed.",
    "Guard against the sunk-cost trap of a question you have already invested time in, because the next question may be worth more per second.",
    "Alternate between easy and difficult items to keep morale steady, since a long run of hard questions erodes the judgement needed for the easy ones.",
    "Reserve the final minutes for the questions you marked rather than for reviewing ones you already answered confidently.",
    "Keep your pacing slightly behind the clock early and slightly ahead of it late, which smooths the usual mid-paper slowdown.",
    "Answer the question that was asked, not the one you expected, because examiners frequently place a familiar setup with an unfamiliar request.",
    "When stuck between two options, reread the stem for the qualifier that distinguishes them, since the deciding detail is usually already present.",
    "Leave a marked question and return with fresh eyes, because the obstacle often dissolves after your attention has moved elsewhere.",
    "Treat the answer options as part of the question, since their differences frequently reveal which concept the examiner intends to test.",
    "Do not let one emotionally charged wrong answer spill into the next item, because recovered focus is worth several marks.",
    "Budget your rough-work space so that a later question does not overwrite an earlier one you may need to revisit.",
    "If two options appear identical, one of them contains a hidden difference in wording or unit, and finding it settles the question.",
    "Use dimensional analysis as a fast filter when options differ in form, since only one can carry the correct combination of units.",
    "Recognise that the paper is designed so that most marks come from the middle band of difficulty, not from its hardest items.",
    "When a calculation grows unwieldy, check whether an exact fraction or a ratio could have carried through instead of a rounded decimal.",
    "Keep a mental note of questions where you hesitated, and return to them before the section ends rather than after.",
    "Breathe deliberately at a transition between sections, because physiological calm improves the precision of the next set of judgements.",
    # common mistakes & traps
    "A frequent error is applying a formula outside the conditions it assumes, so confirm the conditions before trusting the relation.",
    "Another recurring slip is confusing a rate with a total, which is avoidable by labeling every quantity with what it represents per unit.",
    "Candidates often lose marks by answering the previous part of a two-part question, so track what each sub-question actually requests.",
    "Mixing up similar-sounding terms is common under fatigue, and the cure is writing the definition once beside the term the first time it appears.",
    "Overlooking a negative sign in coordinate choices quietly reverses results, which is why the convention belongs on paper before the algebra.",
    "Rounding too early inflates error across chained steps, so keep extra digits until the final subtraction or division.",
    "Confusing independent with dependent events produces confident but wrong probabilities, and a simple rewording of the scenario usually exposes the truth.",
    "Assuming a quantity that merely appears constant is actually constant has ruined many otherwise careful solutions; verify it from the stem.",
    "Selecting an option because it looks familiar rather than because it follows from your work is a trap that distractors are built to exploit.",
    "Copying a number incorrectly from the stem to your working is more common than conceptual failure, so glance back at the source after each transcription.",
    "Treating a qualitative question as if it needed a calculation wastes time, and many items are settled by a single logical comparison.",
    "Forgetting to answer the final question after solving it, leaving a blank bubble, is a mechanical loss with no conceptual cost and no excuse.",
    "Ignoring the direction of a vector while computing its magnitude yields a value that looks right but fails the question's actual request.",
    "Using the average of rates as if it were the average of quantities is a classic misapplication that careful unit tracking prevents.",
    "Applying a rule for one type of bond or process to a case that does not share its defining feature is a content error worth drilling away.",
    "Selecting an answer that satisfies part of the constraints but not all of them is common in arrangement questions, so check every clue at the end.",
    "Confusing the base of a logarithm or the reference of an angle between systems produces consistent but incorrect work, and a single labeled restatement prevents it.",
    "Mistaking an approximate relation for an exact one leads to answers that are close but never among the options, which is itself a diagnostic clue.",
    "Letting a previous question's method dictate the current one is a form of mental inertia that a fresh reading of the stem interrupts.",
    "Assuming the diagram is drawn to scale without reading the accompanying note is a risk that verbal qualification is meant to catch.",
    # subject connection & revision
    "Revisit this material alongside its neighbouring chapter, because questions frequently blend ideas from two topics in a single item.",
    "Link each formula to the physical situation it describes, since a relation tied to a picture is recalled far more reliably than one tied to a symbol.",
    "When two chapters use similar vocabulary, write a small comparison table so that the terms stop bleeding into one another during revision.",
    "Teach the trickiest part of this topic to an imaginary classmate, because explaining exposes the exact point where your own understanding thins.",
    "Return to foundational definitions whenever a advanced question feels slippery, since most confusion traces back to a term used loosely.",
    "Connect new material to something you already trust, because integration across topics is what the paper ultimately rewards.",
    "Rebuild a difficult derivation from scratch once, then again a day later, until the sequence of steps feels inevitable rather than remembered.",
    "Mark the questions that taught you something genuinely new and star them for a final pre-exam pass.",
    "Notice how often a single principle reappears under different disguises, which is the fastest route to seeing the paper as small.",
    "Keep your notes lean; a page you can reread in two minutes will be reread, while a chapter you wrote but never open will not.",
    "Rehearse the transition between representing a problem algebraically and interpreting the result physically, because the exam tests both directions.",
    "Consolidate scattered formulas into a single map per chapter, arranged by the situation that calls for each one.",
    "Check that your summary still matches your current understanding, because notes written early can fossilise an idea you have since corrected.",
    "Use idle moments to drill definitions and classifications, which are the highest-yield material for the shortest available attention.",
    "Compare two questions that look different but share a skeleton, and write the shared skeleton down as the thing to recognise next time.",
    "After finishing a chapter, close the book and outline its structure from memory; the gaps in your outline are your remaining syllabus.",
    "Watch for places where a shortcut and the long method disagree, because such a conflict always signals an assumption you made silently.",
    "Tie each exception you must memorise to the rule it breaks, so that the pair is recalled as one object instead of two.",
    "Track how the same concept is phrased across different question sets, since varied wording is the exam's main disguise for a familiar idea.",
    "Schedule a full recall session with no notes before the exam, because retrieval under exam conditions is the only rehearsal that transfers.",
    "Build a final-week plan that revises by topic frequency rather than by chapter order, focusing effort where the paper concentrates its marks.",
    "Write down the three mistakes you make most often and eliminate them one at a time, because systemic errors cost more than missing knowledge.",
    "Reserve one evening solely for reading your own error log, since patterns in your mistakes become obvious when the entries are seen together.",
    "Confirm on the last day that your method for every high-frequency question type is settled, and leave genuinely open questions unreviewed.",
    "Sleep before the exam is part of the strategy, because a tired mind misreads the very qualifiers you have trained to notice.",
    "Walk into the paper expecting a spread of difficulty, and let the easy questions confirm your rhythm before the harder ones test it.",
    "Trust the process you have practised rather than improvising a new one under the clock, because familiarity itself is a form of speed.",
]
