"""Per-page authored knowledge for subjects and chapters (expanded core text)."""

SUBJECTS = {
    'physics': {
        'chapters': ['Mechanics', 'Heat and Thermodynamics', 'Waves and Optics',
                     'Current Electricity and Magnetism', 'Electrostatics and Capacitors', 'Modern Physics'],
        'core': [
            "Physics in the CEE is the section where conceptual clarity shows up immediately. The examinee is not expected to derive long formulas but to understand what a formula means, when it applies, and what happens when conditions change. A distortion of this understanding is the single most common cause of lost marks: students memorise F = ma and reproduce it under conditions where Newton's laws do not apply unchanged, or apply conservation of energy without checking whether friction is present. The examiners deliberately design options that reward this kind of careless application, which is why purely memorising the syllabus is a losing strategy. Instead, working through each topic with attention to the boundary conditions yields far steadier performance.",
            "Across the six chapters of the physics section, three recurring skills matter. The first is the habit of writing the known and unknown quantities before touching the equation; this converts a vague word problem into a concrete numerical one and prevents confusion between closely related variables such as angular velocity and linear velocity, or magnetic flux and magnetic field. The second is unit awareness, because the CEE freely mixes units such as centimetres and metres, grams and kilograms, or calories and joules, and an unanswered conversion silently destroys what would otherwise be a correct answer. The third is dimensional reasoning, which lets a candidate eliminate wrong options instantly: if a question about kinetic energy has an option whose units are not joules, that option cannot be right regardless of the numbers involved.",
            "Preparation works best in three layers. The first layer is concept consolidation: read each chapter, derive the two or three governing relations from first principles, and list the assumptions that the derivation relies on. The second layer is applied practice: solve the chapter-wise question sets on this site and note not only the correct answers but the reasoning that led to them. The third layer is simulated pressure: attempt full timed tests that mix chapters, because the exam experience is about switching mental context rapidly, and the order of topics inside a question paper rarely follows the textbook order. Working in all three layers prevents the common situation of a student who understands a chapter perfectly in isolation yet loses time when the same chapter appears between two unrelated ones.",
            "During the exam itself, the physics section rewards a strategic reading of the paper before attacking it. Identify the numerical questions that require two or more steps and postpone them, because the one-step questions are faster and carry identical marks. Watch the negative marking: in the CEE, a wrong answer costs marks, so an educated guess is only worthwhile when at least two options can be excluded on solid grounds. Pay special attention to the options themselves, since the examiners frequently reuse the same numerical value with different units, different exponents, or a missing minus sign, and the correct response is often the one that differs from a familiar value by exactly one step.",
            "Repeated errors across practice tests cluster around a small number of habits, and correcting these habits is worth more than attempting twice the questions. The first habit is skipping the question statement's qualifying words, such as ideal, frictionless, at constant temperature, or in vacuum, each of which changes the applicable model. The second is sign and direction errors in vector problems, where a free diagram of forces before writing the equation removes most of the risk. The third is overcounting: in questions about parallel and series combinations, or about lenses and mirrors, it is easy to apply a formula to the wrong object. Building a check-list that covers these three habits transforms a candidate who solves fifty per cent into one who consistently solves eighty per cent.",
        ],
    },
    'chemistry': {
        'chapters': ['Physical Chemistry', 'Inorganic Chemistry', 'Organic Chemistry'],
        'core': [
            "Chemistry in the CEE spans three distinct modes of thinking, and the candidate who recognises which mode a question demands answers it faster. Physical chemistry operates through numbers: equilibrium constants, rates, thermodynamics, and stoichiometry, where a wrong unit or a reversed sign changes everything. Inorganic chemistry operates through patterns: periodic trends, coordination chemistry, and the properties of elements and their compounds, where recall is tested through comparison. Organic chemistry operates through mechanism: functional groups, reactions, and reagents, where understanding why a transformation happens beats memorising individual examples. Each mode needs a different revision diet, and the syllabus naturally splits along these lines.",
            "The physical portion is the most forgiving of systematic practice, because the number of distinct question archetypes is small. Stoichiometry, mole calculations, colligative properties, chemical kinetics, and electrochemistry each reduce to a handful of recurring computations, and a candidate who has solved the site's chapter sets for these topics has almost certainly seen every pattern the paper can offer. The trap is unrealistic shortcuts: skipping the balanced equation, using the wrong value of R, or conflating molarity with molality. Rigorous attention to definition at the start of a computation eliminates most of these errors, and the saved time compounds across the paper.",
            "Inorganic chemistry rewards a periodic-table-first approach. Rather than memorising facts in isolation, anchor each fact to its position in the periodic table: electronegativity trends, ionic radii, oxidation states, and the characteristic colours or compounds of the main groups and the transition series. Questions here often present two elements and ask for the one with the larger radius or the stronger base, and the periodic framework answers all of these faster than rote lists. The CEE also favours the chemistry of common substances, such as washing soda, bleaching powder, and baking soda, whose industrial names and formulas appear repeatedly, so a single organised revision of these compounds covers many marks.",
            "Organic chemistry is best revised by mechanism rather than by reaction list, because distinct reactions that share a mechanism are remembered as one idea. Start from the functional group, list the standard reactions it undergoes, and link each reaction to the reagent and condition that selects it. Nomenclature, isomerism, and the identification of products under specific reagents are a recurring pattern in the paper. When a reaction scheme appears twice in different chapters, such as reduction by a metal hydride in carbonyl and in nitrile chemistry, noticing the connection cements both.",
            "Finally, exam strategy for chemistry mirrors the structure of the paper. Attempt the one-step numericals early, leave multi-component problems for later, and treat negative marking with respect. Use elimination strongly: options that violate periodic trends, break a mechanism, or contradict stoichiometry are provably wrong. Reading the question twice during practice is wasteful, but reading it once with complete attention is never wasteful, because chemistry questions frequently hide the deciding detail in a clause.",
        ],
    },
    'zoology': {
        'chapters': ['General Zoology', 'Human Physiology'],
        'core': [
            "Zoology in the CEE is a recall-driven section where organised memory outperforms breadth. The paper rewards candidates who can place every animal and every physiological process in its correct taxonomic and anatomical context. Animals are tested through their distinctive features, their body systems, and the phyla or classes they represent, while physiology is tested through the path of a substance or a signal through the body. Because both kinds of question depend on the same underlying map of the animal kingdom and the human body, revision that draws this map once and then repeatedly annotates it is far more efficient than reading endless notes.",
            "For the portion of the syllabus that deals with the animal kingdom, the organising principle is the level of organisation: whether an animal is unicellular or multicellular, whether it has tissues, organs, or organ systems, and how symmetry and segmentation progress through the phyla. A question about a specific animal, such as a flatworm or an arthropod, is usually answered by recalling its place on this ladder plus the single defining feature that distinguishes its group. Tabular revision, where a row per phylum lists symmetry, germ layers, body cavity, and one or two classic examples, turns a large list into a small table, and the table is what survives under exam pressure.",
            "Human physiology is tested through pathways and feedback, and the two organising questions for every system are: what moves, and what controls it? For digestion, food moves through organs and is broken down by enzymes secreted in sequence; for circulation, blood moves through chambers and vessels, and valves define the direction; for respiration, air moves along a gradient of pressure, and oxygen attaches to haemoglobin reversibly. When each system is revised as a pathway with control points, the questions about the next step in the pathway and the effect of a broken step answer themselves.",
            "Endocrine and nervous coordination also follow the pathway logic. Hormones are tested by their source gland, their target organ, and their effect, while neurons and reflexes are tested by the sequence of events from stimulus to response. The CEE regularly asks which gland secretes which hormone, which hormone raises blood glucose, and which part of the brain controls which function, all of which are better organised as a source-target-effect table than as a list.",
            "Exam-day strategy for zoology leans on confident recall and disciplined elimination. Because options in recall questions are often one word apart, read the exact wording of the stem: a question that asks for the structure not part of a system is answered by finding the one option that does not belong. Where a numerical or developmental question appears, such as the number of chambers or the stages in a life cycle, anchor the answer to a fact you can verify from a second system rather than guessing. Negative marking applies equally to every answer, so a blank is better than a confident wrong answer, but a reasoned elimination of two options turns the remaining fifty per cent guess into a rational choice.",
        ],
    },
    'botany': {
        'chapters': ['General Botany', 'Plant Physiology'],
        'core': [
            "Botany in the CEE shares the recall-heavy style of zoology but adds its own emphasis on processes that are invisible unless traced carefully, such as transport, photosynthesis, and respiration in plants. The section therefore rewards two complementary skills: precise recall of structures and their functions, and the ability to trace a substance, a water molecule, a mineral ion, or a respiratory substrate through the plant body. Candidates who revise plant structure and plant function as a single connected story, rather than as two unrelated lists, answer a consistently larger fraction of the questions with confidence.",
            "Structure in botany is layered from the cell outward. Within the cell, the organelles and their roles form the first layer; tissues, including meristematic and permanent tissues, form the next; and the whole plant is organised into root, stem, leaf, and reproductive structures in the third. A question that names a cell organelle or a tissue type is usually answered by recalling its distinctive role, and the CEE favours the classic pairings such as the chloroplast with photosynthesis, the mitochondria with respiration, and the xylem with water transport. A quick internal sketch of a labelled cell or a labelled transverse section during revision fixes these roles far better than passive reading.",
            "Plant physiology is best revised as a set of movements. Water moves from soil to atmosphere along a gradient driven by transpiration, minerals move with the water into the root and are carried upward, and the products of photosynthesis move through the phloem. Photosynthesis and respiration each consist of a few stages with defined locations and end products, and questions about dark and light reactions, or about aerobic and anaerobic respiration, are answered by locating the stage and its product rather than by recalling isolated facts.",
            "Life processes in plants also include growth regulators and movement: auxins, gibberellins, cytokinins, abscisic acid, and ethylene each have a signature effect, and their interactions are a favourite comparison. The CEE frequently asks which hormone promotes which growth response, and a compact source-effect table translates a fuzzy memory into a precise answer. Reproduction, whether vegetative or sexual, is tested through the structures involved and the sequence of events, with the flower's parts and the process of pollination, fertilisation, and fruit formation forming the standard storyline.",
            "Exam strategy for botany borrows from zoology: rely on structured tables, read stems precisely, and eliminate options by confirming the defining feature. When two options differ by a single word, such as osmosis versus diffusion or aerobic versus anaerobic, the stem usually contains the deciding clue, and returning to the stem before answering is the cheapest insurance available. As elsewhere, negative marking means that confidence should be earned, and a candidate who answers ten certain questions and leaves five doubtful ones scores higher than one who answers all fifteen on instinct.",
        ],
    },
    'mat': {
        'chapters': ['Numerical Reasoning', 'Verbal Reasoning Test', 'Logical Sequencing',
                     'Spatial Relation/Abstract Reasoning'],
        'core': [
            "The Mental Ability Test is the section of the CEE where speed is the primary currency and pattern recognition decides the outcome. It does not demand advanced mathematics or memorised theory; it demands the ability to see a rule, apply it once, and move on. Because the section is fast and carries full negative marking, developing a personal rhythm, in which easy questions are answered cleanly and harder pattern questions are approached with a fixed method, is worth more than attempting every question. The pages in this subject organise the full MAT syllabus into four chapters of related skills, and each solved set is designed to be attempted under time.",
            "Numerical reasoning deals with the arithmetic of everyday life: time and work, percentage, profit and loss, ratio, ages, averages, speed, interest, and counting problems. These are the most forgiving questions in the section, because the number of methods is small and every method can be practised to automation. The candidate who has solved the chapter sets on these topics has a large statistical advantage, because the CEE repeats the same templates with different numbers, and recognising a template is the difference between a thirty-second answer and a three-minute struggle.",
            "Verbal reasoning moves the section away from numbers into words: coding and decoding, ranking order, analogies, classification, word puzzles, blood relations, and the rest. The skill here is not vocabulary alone but the ability to infer a rule from examples and apply it to a fresh case. Each topic rewards a small fixed method: draw the family tree for blood relations, sketch the path for distance and direction, write the code's rule before decoding the target. Methodical application matters more than guesswork, and the solved sets demonstrate each method on real questions.",
            "Logical sequencing combines number, letter, and word patterns with arrangement puzzles such as series, matrices, and missing-character grids. The unifying technique is to look for the difference or the transformation first: consecutive differences in a number series, letter positions in an alphabet series, row and column rules in a matrix. Arrangement questions yield to the same discipline: write each clue as a constraint and combine them in order of strength.",
            "Spatial and abstract reasoning completes the subject with figures: rotations, folds, cubes and dice, embedded figures, mirror and water images. These test mental manipulation rather than knowledge, and they improve quickly with practice because the set of transformations asked is small. The exam-day reality of MAT is that it is often attempted first or last by candidates, and either way, steady rhythm and disciplined guessing under the section's negative marking separate the top scores from the pack.",
        ],
    },
}