release: python manage.py migrate --noinput && python manage.py submit_indexnow --quiet
web: gunicorn CEE.wsgi:application --access-logfile - --access-logformat '%({x-forwarded-for}i)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'
