"""
Django settings for CEE project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import secrets
import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() == "true"

# SECURITY WARNING: keep the secret key used in production secret!
# Support both common env var names used in Django deployments.
SECRET_KEY = (os.environ.get("SECRET_KEY") or os.environ.get("DJANGO_SECRET_KEY") or "").strip()
if not SECRET_KEY:
    if DEBUG:
        # Dev fallback only; production must provide SECRET_KEY via environment.
        SECRET_KEY = secrets.token_urlsafe(64)
    else:
        raise RuntimeError(
            "SECRET_KEY (or DJANGO_SECRET_KEY) environment variable must be set when DEBUG is False"
        )

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "pandeyramu.com.np",
    "ceemcq.pandeyramu.com.np",
    ".onrender.com",
]

CSRF_TRUSTED_ORIGINS = [
    "https://ramup.com.np",
    "https://www.ramup.com.np",
    "https://pandeyramu.com.np",
    "https://*.onrender.com",
]

# Canonical site URL used in templates and structured data
SITE_URL = os.environ.get('SITE_URL', 'https://pandeyramu.com.np')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'CEE_Quiz',
    'django.contrib.sites',
    'django.contrib.sitemaps',
]

# Let sitemap generation use the incoming request host instead of a hard-coded
# Site row, which avoids a 500 when the django_site table is missing or stale.
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'CEE.middleware.SecurityHeadersMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
]

ROOT_URLCONF = 'CEE.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'CEE_Quiz.context_processors.page_seo',
                'CEE_Quiz.context_processors.site_url',
            ],
        },
    },
]

WSGI_APPLICATION = 'CEE.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
import socket as _socket

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL', f'sqlite:///{BASE_DIR}/db.sqlite3'),
        conn_max_age=600,
        conn_health_checks=True,
    )
}

if DATABASES['default']['ENGINE'] == 'django.db.backends.postgresql':
    DATABASES['default'].setdefault('OPTIONS', {})
    DATABASES['default']['OPTIONS']['options'] = '-c search_path=public'
    _host = DATABASES['default'].get('HOST', '')
    if _host:
        try:
            _ipv4 = _socket.getaddrinfo(_host, None, _socket.AF_INET)
            if _ipv4:
                DATABASES['default']['OPTIONS']['hostaddr'] = _ipv4[0][4][0]
        except OSError:
            pass

# Session Configuration - Extended for long tests
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_COOKIE_AGE = 14400  # 4 hours in seconds
SESSION_SAVE_EVERY_REQUEST = False  # Avoid DB write on every request for better response times
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_SECURE = not DEBUG  # Use secure cookies in production
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = not DEBUG
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True

# CSRF Configuration - Extended timeout
CSRF_COOKIE_AGE = 14400  # 4 hours
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kathmandu'

USE_I18N = True

USE_TZ = True

# In-process cache for immutable quiz question sets, full-test id buckets, and
# near-static SEO lookup rows. Keeps repeat page loads (active quiz refreshes,
# results pages) off Postgres and cuts Supabase database egress.
# LocMemCache is per-process; fine for a single web instance on Render.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'cee-quiz-cache',
        'TIMEOUT': 3600,
        'OPTIONS': {
            'MAX_ENTRIES': 20000,
        },
    },
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

WHITENOISE_MAX_AGE = 86400  # 1 day (no hash busting, so shorter cache)

# Email configuration for question review reports
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '').strip() or 'smtp.gmail.com'
EMAIL_PORT = int((os.environ.get('EMAIL_PORT', '') or '587').strip())
EMAIL_USE_TLS = (os.environ.get('EMAIL_USE_TLS', 'True') or 'True').strip().lower() == 'true'
EMAIL_TIMEOUT = int((os.environ.get('EMAIL_TIMEOUT', '') or '10').strip())
EMAIL_HTTP_TIMEOUT = int((os.environ.get('EMAIL_HTTP_TIMEOUT', '') or '10').strip())
EMAIL_HOST_USER = (os.environ.get('EMAIL_HOST_USER', '') or '').strip()
EMAIL_HOST_PASSWORD = (os.environ.get('EMAIL_HOST_PASSWORD', '') or '').strip()
DEFAULT_FROM_EMAIL = (os.environ.get('DEFAULT_FROM_EMAIL', '') or EMAIL_HOST_USER or 'no-reply@ceequiz.local').strip()
REPORT_TO_EMAIL = (os.environ.get('REPORT_TO_EMAIL', '') or 'ceequiz9830@gmail.com').strip()
REPORT_EMAIL_PROVIDER = (os.environ.get('REPORT_EMAIL_PROVIDER', '') or 'resend').strip().lower()
RESEND_API_KEY = (os.environ.get('RESEND_API_KEY', '') or '').strip()
RESEND_API_URL = (os.environ.get('RESEND_API_URL', '') or 'https://api.resend.com/emails').strip()

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}