# Generated by Django 6.0 on 2026-05-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CEE_Quiz', '0002_chapter_slug_subchapter_slug_subject_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_slug', models.CharField(max_length=100, unique=True)),
                ('meta_title', models.CharField(max_length=70)),
                ('meta_description', models.CharField(max_length=160)),
                ('meta_keywords', models.TextField()),
                ('og_title', models.CharField(blank=True, max_length=70)),
                ('og_description', models.CharField(blank=True, max_length=160)),
            ],
        ),
        migrations.AddField(
            model_name='subchapter',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
    ]
