# Generated by Django 6.0 on 2026-03-13 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CEE_Quiz', '0003_alter_question_correct_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='has_subchapters',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SubChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subchapters', to='CEE_Quiz.chapter')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='sub_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='CEE_Quiz.subchapter'),
        ),
    ]
