# Generated by Django 6.0.5 on 2026-07-10 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CEE_Quiz', '0005_questionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='intro_text',
            field=models.TextField(blank=True, help_text='150-300 word intro for the chapter page'),
        ),
        migrations.AddField(
            model_name='subject',
            name='intro_text',
            field=models.TextField(blank=True, help_text='150-300 word intro for the subject page'),
        ),
        migrations.CreateModel(
            name='SolutionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('intro_text', models.TextField(blank=True, help_text='3-5 sentence intro describing what topics this batch covers')),
                ('question_ids', models.TextField(help_text='Comma-separated list of question IDs in this set')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_sets', to='CEE_Quiz.chapter')),
            ],
            options={
                'ordering': ['chapter', 'set_number'],
                'unique_together': {('chapter', 'set_number')},
            },
        ),
    ]
