# Generated by Django 6.0.5 on 2026-07-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CEE_Quiz', '0006_chapter_intro_text_subject_intro_text_solutionset'),
    ]

    operations = [
        migrations.AddField(
            model_name='subchapter',
            name='intro_text',
            field=models.TextField(blank=True, help_text='150-300 word intro for the subchapter page'),
        ),
    ]
