# Generated by Django 6.0 on 2026-08-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CEE_Quiz', '0017_update_full_test_page_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='verified',
            field=models.BooleanField(default=False, help_text='Mark as verified after manually confirming correctness'),
        ),
    ]
