# Generated by Django 6.0.5 on 2026-09-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CEE_Quiz', '0018_question_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='client_ip',
            field=models.CharField(blank=True, default='', help_text='Client IP from X-Forwarded-For', max_length=45),
        ),
    ]
